from .config import ExecutorConfig, SchedulerConfig, StorageConfig, TelemetryConfig
from .contracts import (
    CheckpointManager,
    EBPFEventCollector,
    FileSystemCWorker,
    FileSystemRWorker,
    ProcessCWorker,
    ProcessRWorker,
    RequestInterceptorHook,
    Runtime,
    SandboxInspector,
    TelemetrySink,
)
from .executor import CRExecutor
from .errors import (
    ImageAuthenticationError,
    ImageCompatibilityError,
    ImageInsufficientDiskError,
    ImageNotFoundError,
    ImagePlatformError,
    ImagePolicyError,
    ImagePullError,
    ImagePullTimeoutError,
    ImageRateLimitError,
    ImageReferenceError,
    ImageTooLargeError,
    SandboxCreateCleanupError,
    SandboxExecCleanupError,
    SandboxExecTimeout,
    SandboxImageError,
)
from .ids import CheckpointId, JobId, SandboxId
from .inspector import EBPFSandboxInspector, InMemoryEBPFEventCollector, InMemorySandboxInspector
from .interceptor import (
    CrabRequestInterceptor,
    CrabRequestInterceptorServer,
    CompositeRequestInterceptorHook,
    InMemoryRequestStateStore,
    RequestAwareSandboxInspector,
    SandboxResponseGateRegistry,
    TelemetryRequestInterceptorHook,
)
from .remote_inspector import HostInspectorServiceClient, RemoteSandboxInspector
from .models import (
    ArtifactKind,
    ArtifactPayload,
    ArtifactReference,
    CheckpointJob,
    CheckpointManifest,
    CheckpointResult,
    EBPFEvent,
    EBPFEventKind,
    FailureCode,
    JobRecord,
    JobStatus,
    JobType,
    RequestContext,
    RequestState,
    RequestStateChange,
    RestoreJob,
    RestoreResult,
    RuntimeCapabilities,
    RuntimeOperationStatus,
    SandboxDescription,
    SandboxExecResult,
    SandboxInfo,
    SandboxRuntimeState,
    SandboxSnapshot,
    SandboxState,
    SchedulerCheckpointDecision,
    sandbox_state_from_status,
)
from .runtime import (
    CommandRunner,
    InMemoryRuntime,
    RuncCheckpointOptions,
    RuncRestoreOptions,
    RuncRuntime,
    RuncRuntimeOptions,
    RuncRuntimePaths,
    SubprocessCommandRunner,
)
from .scheduler import (
    CRScheduler,
    FaultToleranceCheckpointingPolicy,
    InMemorySchedulerStateStore,
    SpotPreemptionCheckpointingPolicy,
    TreeSearchCheckpointingPolicy,
)
from .storage import (
    DeleteAfterRestoreCheckpointManager,
    KeepAllCheckpointManager,
    LatestOnlyCheckpointManager,
    LocalCheckpointManager,
)
from .system import CrabSystem, build_default_system
from .telemetry import (
    AsyncJsonlTelemetrySink,
    CompositeTelemetrySink,
    ConfiguredTelemetrySink,
    InMemoryTelemetrySink,
    JsonlTelemetrySink,
    NoopTelemetrySink,
    build_configured_telemetry_sink,
    start_operation,
)
from .workers import (
    AdapterFileSystemCWorker,
    AdapterFileSystemRWorker,
    AdapterProcessCWorker,
    AdapterProcessRWorker,
    DefaultCWorker,
    DefaultRWorker,
)

# User-facing SDK surface. Sandbox owns sandbox lifecycle; Agent instances are
# bound to an existing sandbox with `agent.bind(sbx, llm_url=...)`.
from .agent import (
    Agent,
    TaskResult,
    list_agents,
    register_agent,
    resolve_agent,
)
from .engine import (
    Engine,
    EngineConfig,
    get_default_engine,
    set_default_engine,
    shutdown_default_engine,
)
from .sandbox import Sandbox
from .txn import (
    Transaction,
    TxnAbortError,
    TxnActiveError,
    TxnError,
    TxnMismatchError,
    TxnResolvedError,
)

# Eager import so the side-effect registrations land before the user
# references any name from this module.
from . import agents_builtin as _agents_builtin  # noqa: F401

__all__ = [
    "Agent",
    "Engine",
    "EngineConfig",
    "Sandbox",
    "SandboxCreateCleanupError",
    "SandboxExecCleanupError",
    "SandboxExecTimeout",
    "SandboxImageError",
    "ImageAuthenticationError",
    "ImageCompatibilityError",
    "ImageInsufficientDiskError",
    "ImageNotFoundError",
    "ImagePlatformError",
    "ImagePolicyError",
    "ImagePullError",
    "ImagePullTimeoutError",
    "ImageRateLimitError",
    "ImageReferenceError",
    "ImageTooLargeError",
    "Transaction",
    "TxnAbortError",
    "TxnActiveError",
    "TxnError",
    "TxnMismatchError",
    "TxnResolvedError",
    "TaskResult",
    "get_default_engine",
    "list_agents",
    "register_agent",
    "resolve_agent",
    "set_default_engine",
    "shutdown_default_engine",
    "CrabSystem",
    "ArtifactKind",
    "ArtifactPayload",
    "ArtifactReference",
    "CheckpointId",
    "CheckpointJob",
    "CheckpointManager",
    "CheckpointManifest",
    "CheckpointResult",
    "CRExecutor",
    "CRScheduler",
    "EBPFEvent",
    "EBPFEventCollector",
    "EBPFEventKind",
    "EBPFSandboxInspector",
    "DefaultCWorker",
    "DefaultRWorker",
    "DeleteAfterRestoreCheckpointManager",
    "ExecutorConfig",
    "FaultToleranceCheckpointingPolicy",
    "FailureCode",
    "FileSystemCWorker",
    "FileSystemRWorker",
    "InMemorySandboxInspector",
    "InMemoryEBPFEventCollector",
    "InMemoryRuntime",
    "InMemorySchedulerStateStore",
    "InMemoryTelemetrySink",
    "JsonlTelemetrySink",
    "ConfiguredTelemetrySink",
    "JobId",
    "JobRecord",
    "JobStatus",
    "JobType",
    "KeepAllCheckpointManager",
    "LatestOnlyCheckpointManager",
    "LocalCheckpointManager",
    "HostInspectorServiceClient",
    "NoopTelemetrySink",
    "ProcessCWorker",
    "ProcessRWorker",
    "RequestContext",
    "RequestState",
    "RequestStateChange",
    "RequestInterceptorHook",
    "Runtime",
    "RestoreJob",
    "RestoreResult",
    "RuncCheckpointOptions",
    "RuncRuntime",
    "RuncRestoreOptions",
    "RuncRuntimeOptions",
    "RuncRuntimePaths",
    "RuntimeCapabilities",
    "RuntimeOperationStatus",
    "SandboxDescription",
    "SandboxExecResult",
    "SandboxId",
    "SandboxInfo",
    "SandboxInspector",
    "SandboxRuntimeState",
    "SandboxSnapshot",
    "SandboxState",
    "SchedulerCheckpointDecision",
    "SchedulerConfig",
    "sandbox_state_from_status",
    "SpotPreemptionCheckpointingPolicy",
    "StorageConfig",
    "SubprocessCommandRunner",
    "TelemetryConfig",
    "TelemetrySink",
    "CompositeTelemetrySink",
    "CommandRunner",
    "build_default_system",
    "AdapterProcessCWorker",
    "AdapterProcessRWorker",
    "AdapterFileSystemCWorker",
    "AdapterFileSystemRWorker",
    "AsyncJsonlTelemetrySink",
    "CompositeRequestInterceptorHook",
    "CrabRequestInterceptor",
    "InMemoryRequestStateStore",
    "RequestAwareSandboxInspector",
    "RemoteSandboxInspector",
    "SandboxResponseGateRegistry",
    "TelemetryRequestInterceptorHook",
    "TreeSearchCheckpointingPolicy",
    "CrabRequestInterceptorServer",
    "build_configured_telemetry_sink",
    "start_operation",
]
